from typing import Protocol
from uuid import UUID

from src.domain.entities.category import Category


class CategoryRepository(Protocol):
    async def get_by_id(self, tenant_id: UUID, category_id: UUID) -> Category | None: ...

    async def get_by_slug(self, tenant_id: UUID, slug: str) -> Category | None: ...

    async def list(self, tenant_id: UUID) -> list[Category]: ...

    async def add(self, category: Category) -> Category: ...

    async def update(self, category: Category) -> Category: ...

    async def delete(self, tenant_id: UUID, category_id: UUID) -> None: ...
