from typing import Protocol


class Cache(Protocol):
    async def get(self, key: str) -> str | None: ...

    async def set(self, key: str, value: str, ttl_seconds: int) -> None: ...

    async def get_version(self, namespace: str) -> int: ...

    async def bump_version(self, namespace: str) -> None: ...
